server:
  port: 8888
  servlet:
    context-path: /
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 2
  pool:
    max-active: 11
    max-wait: -1
    max-idle: 20
    min-idle: 0
    maxIdle: 50
    minIdle: 10
    maxActive: 500
    maxWait: 300
    testOnBorrow: true
    testOnReturn: false
shiro:
  authc:
    credential:
      hash-algorithm: SHA-256
      hash-iterations: 1024
      stored-credentials-hex-encoded: false
