server:
  port: 8888
  servlet:
    context-path: /
spring:
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    database: 2
  pool:
    max-active: 11
    max-wait: -1
    max-idle: 20
    min-idle: 0
    maxIdle: 50
    minIdle: 10
    maxActive: 500
    maxWait: 300
    testOnBorrow: true
    testOnReturn: false
shiro:
  authc:
    hash-algorithm: SHA-256
    hash-iterations: 1024
    stored-credentials-hex-encoded: false
  filter:
    login-url: /login
    success-url: /
    unauthorized-url: /403
    filter-chain-map:
      /user/login : anon
      /logout : anon
      /resources/** : anon
      /password/** : anon
      /password.html : anon
      /captcha.jpg : anon
      /favicon.ico : anon
      /favi.ico : anon
      /login/sendCode : anon
      /login/valid.json : anon
